<a href="https://colab.research.google.com/github/bathula-sushmareddy/Brainwave_Matrix_Intern/blob/main/Fake_News_Detection_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

About the dataset

1.Title: title of news article

2.Text: body text of news article

3.Subject: subject of news article

4.Date: publish date of news article

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [ ]:
df_fake=pd.read_csv('/content/Fake.csv',engine='python',on_bad_lines='skip')

In [ ]:
df_true=pd.read_csv('/content/True.csv',engine='python',on_bad_lines='skip')

In [ ]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [ ]:
df_fake.shape,df_true.shape

((6953, 4), (2065, 4))

In [ ]:
df_true.isnull().sum(),df_fake.isnull().sum()

(title      0
 text       0
 subject    0
 date       0
 dtype: int64,
 title      0
 text       0
 subject    0
 date       0
 dtype: int64)

In [ ]:
df_fake['class']=0
df_true['class']=1

In [ ]:
data=pd.concat([df_fake,df_true],axis=0)

In [ ]:
data.shape

(9018, 5)

In [ ]:
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
data.head()

title  \
0   Alabama Republican Governor BUSTED Lying To C...   
1   Bernie Sanders Lets Chuck Todd Know If He’s W...   
2   Paul Ryan Takes A Monumentally HUMILIATING Ph...   
3   Trump Supporter In Phoenix Just Threatened Jo...   
4   This North Carolina High School Just Made It ...   

                                                text subject             date  \
0  They say the cover-up is always worse than the...    News  August 12, 2016   
1  With the Democratic primary process drawing to...    News     May 29, 2016   
2  Politicians are all about photo-ops. This is e...    News      May 7, 2017   
3  Donald Trump, in his ongoing effort to spur on...    News  August 22, 2017   
4  It s hard to believe that so many people are s...    News     May 11, 2016   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [ ]:
data.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [ ]:
data=data.drop(['title','subject','date'],axis=1)

In [ ]:
data.head()

text  class
0  They say the cover-up is always worse than the...      0
1  With the Democratic primary process drawing to...      0
2  Politicians are all about photo-ops. This is e...      0
3  Donald Trump, in his ongoing effort to spur on...      0
4  It s hard to believe that so many people are s...      0

In [ ]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [ ]:
data.columns

Index(['text', 'class'], dtype='object')

In [ ]:
data.reset_index(inplace=True)
data.drop(['index'],axis=1,inplace=True)

In [ ]:
data.columns

Index(['text', 'class'], dtype='object')

In [ ]:
data.head()

text  class
0  They say the cover-up is always worse than the...      0
1  With the Democratic primary process drawing to...      0
2  Politicians are all about photo-ops. This is e...      0
3  Donald Trump, in his ongoing effort to spur on...      0
4  It s hard to believe that so many people are s...      0

In [ ]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\[.*?\]', '', text)       # Remove text in brackets
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # Remove URLs
    text = re.sub(r'<.*?>+', '', text)         # Remove HTML tags
    text = re.sub(r'[^a-z\s]', '', text)       # Remove special characters
    return text

In [ ]:
data['text']=data['text'].apply(clean_text)

In [ ]:
x=data['text']
y=data['class']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X= vectorizer.fit_transform(x_train)
Y=vectorizer.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [ ]:
model.fit(X,y_train)
model.score(Y,y_test)

0.9920177383592018

In [ ]:
model.predict(Y)

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
print(classification_report(y_test,model.predict(Y)))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1727
           1       1.00      0.97      0.98       528

    accuracy                           0.99      2255
   macro avg       0.99      0.98      0.99      2255
weighted avg       0.99      0.99      0.99      2255



In [ ]:
from sklearn.tree import DecisionTreeClassifier
model2=DecisionTreeClassifier()
model2.fit(X,y_train)
model2.score(Y,y_test)

0.9977827050997783

In [ ]:
model2.predict(Y)

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
print(classification_report(y_test,model2.predict(Y)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1727
           1       1.00      0.99      1.00       528

    accuracy                           1.00      2255
   macro avg       1.00      1.00      1.00      2255
weighted avg       1.00      1.00      1.00      2255



In [ ]:
from sklearn.ensemble import RandomForestClassifier
model3=RandomForestClassifier()
model3.fit(X,y_train)
model3.score(Y,y_test)

0.985809312638581

In [ ]:
model3.predict(Y)

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
print(classification_report(y_test,model3.predict(Y)))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1727
           1       1.00      0.94      0.97       528

    accuracy                           0.99      2255
   macro avg       0.99      0.97      0.98      2255
weighted avg       0.99      0.99      0.99      2255



In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model4=GradientBoostingClassifier()
model4.fit(X,y_train)
model4.score(Y,y_test)

0.9982261640798226

In [ ]:
model4.predict(Y)

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
print(classification_report(y_test,model4.predict(Y)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1727
           1       1.00      1.00      1.00       528

    accuracy                           1.00      2255
   macro avg       1.00      1.00      1.00      2255
weighted avg       1.00      1.00      1.00      2255



In [ ]:
def get_label(n):
    return "Fake" if n == 0 else "True"

def manual_testing(news):
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(clean_text)
    new_x_test = vectorizer.transform(new_def_test["text"])
    pred_LR = model.predict(new_x_test)[0]
    pred_DT = model2.predict(new_x_test)[0]
    pred_RF = model3.predict(new_x_test)[0]

    print(f"Logistic Regression Prediction: {get_label(pred_LR)}")
    print(f"Decision Tree Prediction: {get_label(pred_DT)}")
    print(f"Random Forest Prediction: {get_label(pred_RF)}")
print(data['class'].value_counts())

class
0    6953
1    2065
Name: count, dtype: int64


In [ ]:
manual_testing("The Prime Minister announced a new economic stimulus package to boost the post-pandemic recovery.")


Logistic Regression Prediction: True
Decision Tree Prediction: Fake
Random Forest Prediction: True


In [ ]:
manual_testing("NASA confirms water molecules detected on the sunlit surface of the Moon, paving the way for future missions.")


Logistic Regression Prediction: Fake
Decision Tree Prediction: Fake
Random Forest Prediction: True


In [ ]:
manual_testing("Scientists discover a pill that instantly makes people invisible for 24 hours, now available in local pharmacies.")


Logistic Regression Prediction: Fake
Decision Tree Prediction: Fake
Random Forest Prediction: True
